<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    
    use Favoritable, RecordActivity ;
    
    protected $guarded = [];
    protected $with = ['owner','favorites'];
    protected $appends = ['favoritesCount','isFavorited'];
    
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function($reply){
            $reply->thread->increment('replies_count');
        });
        static::deleted(function($reply){
            $reply->thread->decrement('replies_count');
        });
    }
    
    
    //
    public function owner()
    {
        return $this->belongsTo('App\User', 'user_id');
    }
    
    public function thread()
    {
        return $this->belongsTo('App\Thread');
    }
    
    public function path(){
        return $this->thread->path()."#reply-{$this->id}";
    }
    
    public function wasJustPublished()
    {
        return $this->created_at->gt(Carbon::now()->subMinute());
    }
    
    
}
